- name: create ec2 and r53
  hosts: localhost
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-07c8acf3fa6b923fa # replace with your SG ID
    zone_id: "Z0948150OFPSYTNVYZOY" # replace with your ID
    domain_name: "daws86s.fun"
    instances: 
    - mongodb
    - redis
    - mysql
    - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

